### ISSUE TITLE
Background is inappropriate

### ISSUE THREAD

**Issue by balAdamT** [clover-ly/clover-ly.github.io#2]
Add a picture of summer Socie to the background to increase the concentration of the visitors and thus improve site browsing experience,

**Comment by clover-ly** [comment]
intial testing deemed this distracting:
![ss](https://user-images.githubusercontent.com/10272157/58766245-3da7ec00-854a-11e9-84ad-c597dc6eb28a.png)

a proposed revision to your idea that might work better:
![ss2](https://user-images.githubusercontent.com/10272157/58766253-4698bd80-854a-11e9-9c5b-3a70047d2d2e.png)

**Comment by balAdamT** [comment]
:frogger: 
Not distracting at all. Just put some transparency on those UI elements and it will be good :somasilly:
